/* GET USER TYPES */
export const GET_USER_TYPES = "GET_USER_TYPES"
export const GET_USER_TYPES_SUCCESS = "GET_USER_TYPES_SUCCESS"
export const GET_USER_TYPES_FAIL = "GET_USER_TYPES_FAIL"

/* USERS */
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const ADD_USER = "ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const DISABLE_USER = "DISABLE_USER"
export const DISABLE_USER_SUCCESS = "DISABLE_USER_SUCCESS"
export const DISABLE_USER_FAIL = "DISABLE_USER_FAIL"

export const ENABLE_USER = "ENABLE_USER"
export const ENABLE_USER_SUCCESS = "ENABLE_USER_SUCCESS"
export const ENABLE_USER_FAIL = "ENABLE_USER_FAIL"

/* PLATO USERS */
export const GET_PLATO_USERS = "GET_PLATO_USERS"
export const GET_PLATO_USERS_SUCCESS = "GET_PLATO_USERS_SUCCESS"
export const GET_PLATO_USERS_FAIL = "GET_PLATO_USERS_FAIL"

export const ADD_PLATO_USER = "ADD_PLATO_USER"
export const ADD_PLATO_USER_SUCCESS = "ADD_PLATO_USER_SUCCESS"
export const ADD_PLATO_USER_FAIL = "ADD_PLATO_USER_FAIL"

export const UPDATE_PLATO_USER = "UPDATE_PLATO_USER"
export const UPDATE_PLATO_USER_SUCCESS = "UPDATE_PLATO_USER_SUCCESS"
export const UPDATE_PLATO_USER_FAIL = "UPDATE_PLATO_USER_FAIL"

export const DISABLE_PLATO_USER = "DISABLE_PLATO_USER"
export const DISABLE_PLATO_USER_SUCCESS = "DISABLE_PLATO_USER_SUCCESS"
export const DISABLE_PLATO_USER_FAIL = "DISABLE_PLATO_USER_FAIL"

export const ENABLE_PLATO_USER = "ENABLE_PLATO_USER"
export const ENABLE_PLATO_USER_SUCCESS = "ENABLE_PLATO_USER_SUCCESS"
export const ENABLE_PLATO_USER_FAIL = "ENABLE_PLATO_USER_FAIL"

/* CLINICIANS */
export const GET_CLINICIANS = "GET_CLINICIANS"
export const GET_CLINICIANS_SUCCESS = "GET_CLINICIANS_SUCCESS"
export const GET_CLINICIANS_FAIL = "GET_CLINICIANS_FAIL"

export const GET_CLINICIANS_BY_CLINIC = "GET_CLINICIANS_BY_CLINIC"
export const GET_CLINICIANS_BY_CLINIC_SUCCESS = "GET_CLINICIANS_BY_CLINIC_SUCCESS"
export const GET_CLINICIANS_BY_CLINIC_FAIL = "GET_CLINICIANS_BY_CLINIC_FAIL"

export const ADD_CLINICIAN_USER = "ADD_CLINICIAN_USER"
export const ADD_CLINICIAN_USER_SUCCESS = "ADD_CLINICIAN_USER_SUCCESS"
export const ADD_CLINICIAN_USER_FAIL = "ADD_CLINICIAN_USER_FAIL"

export const UPDATE_CLINICIAN_USER = "UPDATE_CLINICIAN_USER"
export const UPDATE_CLINICIAN_USER_SUCCESS = "UPDATE_CLINICIAN_USER_SUCCESS"
export const UPDATE_CLINICIAN_USER_FAIL = "UPDATE_CLINICIAN_USER_FAIL"

export const DISABLE_CLINICIAN_USER = "DISABLE_CLINICIAN_USER"
export const DISABLE_CLINICIAN_USER_SUCCESS = "DISABLE_CLINICIAN_USER_SUCCESS"
export const DISABLE_CLINICIAN_USER_FAIL = "DISABLE_CLINICIAN_USER_FAIL"

export const ENABLE_CLINICIAN_USER = "ENABLE_CLINICIAN_USER"
export const ENABLE_CLINICIAN_USER_SUCCESS = "ENABLE_CLINICIAN_USER_SUCCESS"
export const ENABLE_CLINICIAN_USER_FAIL = "ENABLE_CLINICIAN_USER_FAIL"

/* MY CLINICIANS */
export const GET_MY_CLINICIANS = "GET_MY_CLINICIANS"
export const GET_MY_CLINICIANS_SUCCESS = "GET_MY_CLINICIANS_SUCCESS"
export const GET_MY_CLINICIANS_FAIL = "GET_MY_CLINICIANS_FAIL"

export const ADD_MY_CLINICIAN = "ADD_MY_CLINICIAN"
export const ADD_MY_CLINICIAN_SUCCESS = "ADD_MY_CLINICIAN_SUCCESS"
export const ADD_MY_CLINICIAN_FAIL = "ADD_MY_CLINICIAN_FAIL"

export const UPDATE_MY_CLINICIAN = "UPDATE_MY_CLINICIAN"
export const UPDATE_MY_CLINICIAN_SUCCESS = "UPDATE_MY_CLINICIAN_SUCCESS"
export const UPDATE_MY_CLINICIAN_FAIL = "UPDATE_MY_CLINICIAN_FAIL"

export const DISABLE_MY_CLINICIAN = "DISABLE_MY_CLINICIAN"
export const DISABLE_MY_CLINICIAN_SUCCESS = "DISABLE_MY_CLINICIAN_SUCCESS"
export const DISABLE_MY_CLINICIAN_FAIL = "DISABLE_MY_CLINICIAN_FAIL"

export const ENABLE_MY_CLINICIAN = "ENABLE_MY_CLINICIAN"
export const ENABLE_MY_CLINICIAN_SUCCESS = "ENABLE_MY_CLINICIAN_SUCCESS"
export const ENABLE_MY_CLINICIAN_FAIL = "ENABLE_MY_CLINICIAN_FAIL"

export const CHECK_CLINICIAN_ADMIN = "CHECK_CLINICIAN_ADMIN"
export const CHECK_CLINICIAN_ADMIN_SUCCESS = "CHECK_CLINICIAN_ADMIN_SUCCESS"
export const CHECK_CLINICIAN_ADMIN_FAIL = "CHECK_CLINICIAN_ADMIN_FAIL"

export const CLEAR_USERS_ERROR = "CLEAR_USERS_ERROR"
export const CLEAR_CLINICIANS = "CLEAR_CLINICIANS"