/* GET CLINICS */
export const GET_CLINICS = "GET_CLINICS"
export const GET_CLINICS_SUCCESS = "GET_CLINICS_SUCCESS"
export const GET_CLINICS_FAIL = "GET_CLINICS_FAIL"

/* GET MY CLINICS */
export const GET_MY_CLINICS = "GET_MY_CLINICS"
export const GET_MY_CLINICS_SUCCESS = "GET_MY_CLINICS_SUCCESS"
export const GET_MY_CLINICS_FAIL = "GET_MY_CLINICS_FAIL"

/**
 * ADD CLINIC
 */
export const ADD_CLINIC = "ADD_CLINIC"
export const ADD_CLINIC_SUCCESS = "ADD_CLINIC_SUCCESS"
export const ADD_CLINIC_FAIL = "ADD_CLINIC_FAIL"

/**
 * EDIT CLINIC
 */
export const UPDATE_CLINIC = "UPDATE_CLINIC"
export const UPDATE_CLINIC_SUCCESS = "UPDATE_CLINIC_SUCCESS"
export const UPDATE_CLINIC_FAIL = "UPDATE_CLINIC_FAIL"

/**
 * DISABLE CLINIC
 */
export const DISABLE_CLINIC = "DISABLE_CLINIC"
export const DISABLE_CLINIC_SUCCESS = "DISABLE_CLINIC_SUCCESS"
export const DISABLE_CLINIC_FAIL = "DISABLE_CLINIC_FAIL"

/**
 * DISABLE CLINIC
 */
export const ENABLE_CLINIC = "ENABLE_CLINIC"
export const ENABLE_CLINIC_SUCCESS = "ENABLE_CLINIC_SUCCESS"
export const ENABLE_CLINIC_FAIL = "ENABLE_CLINIC_FAIL"

export const CLEAN_CLINICS_ERROR = "CLEAN_CLINICS_ERROR";
