/* PLATO COUNTRIES */
export const GET_PLATO_COUNTRIES = "GET_PLATO_COUNTRIES"
export const GET_PLATO_COUNTRIES_SUCCESS = "GET_PLATO_COUNTRIES_SUCCESS"
export const GET_PLATO_COUNTRIES_FAIL = "GET_PLATO_COUNTRIES_FAIL"

export const ADD_PLATO_COUNTRY = "ADD_PLATO_COUNTRY"
export const ADD_PLATO_COUNTRY_SUCCESS = "ADD_PLATO_COUNTRY_SUCCESS"
export const ADD_PLATO_COUNTRY_FAIL = "ADD_PLATO_COUNTRY_FAIL"

export const UPDATE_PLATO_COUNTRY = "UPDATE_PLATO_COUNTRY"
export const UPDATE_PLATO_COUNTRY_SUCCESS = "UPDATE_PLATO_COUNTRY_SUCCESS"
export const UPDATE_PLATO_COUNTRY_FAIL = "UPDATE_PLATO_COUNTRY_FAIL"

export const DISABLE_PLATO_COUNTRY = "DISABLE_PLATO_COUNTRY"
export const DISABLE_PLATO_COUNTRY_SUCCESS = "DISABLE_PLATO_COUNTRY_SUCCESS"
export const DISABLE_PLATO_COUNTRY_FAIL = "DISABLE_PLATO_COUNTRY_FAIL"

export const ENABLE_PLATO_COUNTRY = "ENABLE_PLATO_COUNTRY"
export const ENABLE_PLATO_COUNTRY_SUCCESS = "ENABLE_PLATO_COUNTRY_SUCCESS"
export const ENABLE_PLATO_COUNTRY_FAIL = "ENABLE_PLATO_COUNTRY_FAIL"



export const CLEAR_USERS_ERROR = "CLEAR_USERS_ERROR"