/* PATIENTS */
export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";

export const GET_PATIENT = "GET_PATIENT";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENT_FAIL = "GET_PATIENT_FAIL";

export const ADD_PATIENT = "ADD_PATIENT";
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_FAIL = "ADD_PATIENT_FAIL";
export const RESET_PATIENT_GUID = "RESET_PATIENT_GUID";

export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_FAIL = "UPDATE_PATIENT_FAIL";

export const DISABLE_PATIENT = "DISABLE_PATIENT";
export const DISABLE_PATIENT_SUCCESS = "DISABLE_PATIENT_SUCCESS";
export const DISABLE_PATIENT_FAIL = "DISABLE_PATIENT_FAIL";

export const ENABLE_PATIENT = "ENABLE_PATIENT";
export const ENABLE_PATIENT_SUCCESS = "ENABLE_PATIENT_SUCCESS";
export const ENABLE_PATIENT_FAIL = "ENABLE_PATIENT_FAIL";

/* MY PATIENTS */
export const GET_MY_PATIENTS = "GET_MY_PATIENTS";
export const GET_MY_PATIENTS_SUCCESS = "GET_MY_PATIENTS_SUCCESS";
export const GET_MY_PATIENTS_FAIL = "GET_MY_PATIENTS_FAIL";

export const GET_MY_PATIENT = "GET_MY_PATIENT";
export const GET_MY_PATIENT_SUCCESS = "GET_MY_PATIENT_SUCCESS";
export const GET_MY_PATIENT_FAIL = "GET_MY_PATIENT_FAIL";

export const ADD_MY_PATIENT = "ADD_MY_PATIENT";
export const ADD_MY_PATIENT_SUCCESS = "ADD_MY_PATIENT_SUCCESS";
export const ADD_MY_PATIENT_FAIL = "ADD_MY_PATIENT_FAIL";

export const UPDATE_MY_PATIENT = "UPDATE_MY_PATIENT";
export const UPDATE_MY_PATIENT_SUCCESS = "UPDATE_MY_PATIENT_SUCCESS";
export const UPDATE_MY_PATIENT_FAIL = "UPDATE_MY_PATIENT_FAIL";

export const DISABLE_MY_PATIENT = "DISABLE_MY_PATIENT";
export const DISABLE_MY_PATIENT_SUCCESS = "DISABLE_MY_PATIENT_SUCCESS";
export const DISABLE_MY_PATIENT_FAIL = "DISABLE_MY_PATIENT_FAIL";

export const ENABLE_MY_PATIENT = "ENABLE_MY_PATIENT";
export const ENABLE_MY_PATIENT_SUCCESS = "ENABLE_MY_PATIENT_SUCCESS";
export const ENABLE_MY_PATIENT_FAIL = "ENABLE_MY_PATIENT_FAIL";

/* PATIENT TREATMENTS */
export const GET_PATIENT_TREATMENTS = "GET_PATIENT_TREATMENTS";
export const GET_PATIENT_TREATMENTS_SUCCESS = "GET_PATIENT_TREATMENTS_SUCCESS";
export const GET_PATIENT_TREATMENTS_FAIL = "GET_PATIENT_TREATMENTS_FAIL";

export const ADD_PATIENT_TREATMENT = "ADD_PATIENT_TREATMENT";
export const ADD_PATIENT_TREATMENT_SUCCESS = "ADD_PATIENT_TREATMENT_SUCCESS";
export const ADD_PATIENT_TREATMENT_FAIL = "ADD_PATIENT_TREATMENT_FAIL";

export const DISABLE_PATIENT_TREATMENT = "DISABLE_PATIENT_TREATMENT";
export const DISABLE_PATIENT_TREATMENT_SUCCESS =
  "DISABLE_PATIENT_TREATMENT_SUCCESS";
export const DISABLE_PATIENT_TREATMENT_FAIL = "DISABLE_PATIENT_TREATMENT_FAIL";

export const ENABLE_PATIENT_TREATMENT = "ENABLE_PATIENT_TREATMENT";
export const ENABLE_PATIENT_TREATMENT_SUCCESS =
  "ENABLE_PATIENT_TREATMENT_SUCCESS";
export const ENABLE_PATIENT_TREATMENT_FAIL = "ENABLE_PATIENT_TREATMENT_FAIL";

export const START_PATIENT_TREATMENT = "START_PATIENT_TREATMENT";
export const START_PATIENT_TREATMENT_SUCCESS =
  "START_PATIENT_TREATMENT_SUCCESS";
export const START_PATIENT_TREATMENT_FAIL = "START_PATIENT_TREATMENT_FAIL";

export const END_PATIENT_TREATMENT = "END_PATIENT_TREATMENT";
export const END_PATIENT_TREATMENT_SUCCESS = "END_PATIENT_TREATMENT_SUCCESS";
export const END_PATIENT_TREATMENT_FAIL = "END_PATIENT_TREATMENT_FAIL";

export const GET_INTERVENTIONS_BY_TREATMENT = "GET_INTERVENTIONS_BY_TREATMENT";
export const GET_INTERVENTIONS_BY_TREATMENT_SUCCESS = "GET_INTERVENTIONS_BY_TREATMENT_SUCCESS";
export const GET_INTERVENTIONS_BY_TREATMENT_FAIL = "GET_INTERVENTIONS_BY_TREATMENT_FAIL";

export const CLEAR_PATIENTS_ERROR = "CLEAR_PATIENTS_ERROR";
