export const CLEAN_CLINICIAN_ERROR = "CLEAN_CLINICIAN_ERROR"

/* GET CLINICIAN */
export const GET_CLINICIAN_BY = "GET_CLINICIAN"
export const GET_CLINICIAN_BY_SUCCESS = "GET_CLINICIAN_SUCCESS"
export const GET_CLINICIAN_BY_FAIL = "GET_CLINICIAN_FAIL"

/* GET CLINICIAN CLINICS BY */
export const GET_CLINICIAN_CLINICS_BY = "GET_CLINICIAN_CLINICS_BY"
export const GET_CLINICIAN_CLINICS_BY_SUCCESS = "GET_CLINICIAN_CLINICS_BY_SUCCESS"
export const GET_CLINICIAN_CLINICS_BY_FAIL = "GET_CLINICIAN_CLINICS_BY_FAIL"

/* DISABLE CLINICIAN BY */
export const DISABLE_CLINICIAN_BY = "DISABLE_CLINICIAN_BY"
export const DISABLE_CLINICIAN_BY_SUCCESS = "DISABLE_CLINICIAN_BY_SUCCESS"
export const DISABLE_CLINICIAN_BY_FAIL = "DISABLE_CLINICIAN_BY_FAIL"

/* ENABLE CLINICIAN BY */
export const ENABLE_CLINICIAN_BY = "ENABLE_CLINICIAN_BY"
export const ENABLE_CLINICIAN_BY_SUCCESS = "ENABLE_CLINICIAN_BY_SUCCESS"
export const ENABLE_CLINICIAN_BY_FAIL = "ENABLE_CLINICIAN_BY_FAIL"

/* CREATE RELATIONSHIP */
export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY"
export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS" 
export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL"

/* UDPATE RELATIONSHIP */
export const ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY = "ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY"
export const ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS = "ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS" 
export const ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL = "ADMIN_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL"

/* ENABLE RELATIONSHIP */
export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY"
export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_SUCCESS" 
export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_FAIL"

/* GET CLINICIAN BY ADMIN */
export const GET_CLINICIAN_BY_ADMIN = "GET_CLINICIAN_BY_ADMIN"
export const GET_CLINICIAN_BY_ADMIN_SUCCESS = "GET_CLINICIAN_BY_ADMIN_SUCCESS"
export const GET_CLINICIAN_BY_ADMIN_FAIL = "GET_CLINICIAN_BY_ADMIN_FAIL"

/* GET CLINICIAN CLINICS BY ADMIN */
export const GET_CLINICIAN_CLINICS_BY_ADMIN = "GET_CLINICIAN_CLINICS_BY_ADMIN"
export const GET_CLINICIAN_CLINICS_BY_ADMIN_SUCCESS = "GET_CLINICIAN_CLINICS_BY_ADMIN_SUCCESS"
export const GET_CLINICIAN_CLINICS_BY_ADMIN_FAIL = "GET_CLINICIAN_CLINICS_BY_ADMIN_FAIL"

export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN"
export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_SUCCESS = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_SUCCESS"
export const CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_FAIL = "CREATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_FAIL"

export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN"
export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_SUCCESS = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_SUCCESS" 
export const ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_FAIL = "ACTIVATE_CLINIC_CLINICIAN_RELATIONSHIP_BY_ADMIN_FAIL"
