/* STIMULATIONS */
export const GET_STIMULATIONS = "GET_STIMULATIONS"
export const GET_STIMULATIONS_SUCCESS = "GET_STIMULATIONS_SUCCESS"
export const GET_STIMULATIONS_FAIL = "GET_STIMULATIONS_FAIL"

export const GET_STIMULATION = "GET_STIMULATION"
export const GET_STIMULATION_SUCCESS = "GET_STIMULATION_SUCCESS"
export const GET_STIMULATION_FAIL = "GET_STIMULATION_FAIL"

export const ADD_STIMULATION = "ADD_STIMULATION"
export const ADD_STIMULATION_SUCCESS = "ADD_STIMULATION_SUCCESS"
export const ADD_STIMULATION_FAIL = "ADD_STIMULATION_FAIL"

export const UPDATE_STIMULATION = "UPDATE_STIMULATION"
export const UPDATE_STIMULATION_SUCCESS = "UPDATE_STIMULATION_SUCCESS"
export const UPDATE_STIMULATION_FAIL = "UPDATE_STIMULATION_FAIL"

export const DISABLE_STIMULATION = "DISABLE_STIMULATION"
export const DISABLE_STIMULATION_SUCCESS = "DISABLE_STIMULATION_SUCCESS"
export const DISABLE_STIMULATION_FAIL = "DISABLE_STIMULATION_FAIL"

export const ENABLE_STIMULATION = "ENABLE_STIMULATION"
export const ENABLE_STIMULATION_SUCCESS = "ENABLE_STIMULATION_SUCCESS"
export const ENABLE_STIMULATION_FAIL = "ENABLE_STIMULATION_FAIL"

/* CLINIC STIMULATIONS */
export const GET_CLINIC_STIMULATIONS = "GET_CLINIC_STIMULATIONS"
export const GET_CLINIC_STIMULATIONS_SUCCESS = "GET_CLINIC_STIMULATIONS_SUCCESS"
export const GET_CLINIC_STIMULATIONS_FAIL = "GET_CLINIC_STIMULATIONS_FAIL"

export const GET_CLINIC_STIMULATION = "GET_CLINIC_STIMULATION"
export const GET_CLINIC_STIMULATION_SUCCESS = "GET_CLINIC_STIMULATION_SUCCESS"
export const GET_CLINIC_STIMULATION_FAIL = "GET_CLINIC_STIMULATION_FAIL"

export const ADD_CLINIC_STIMULATION = "ADD_CLINIC_STIMULATION"
export const ADD_CLINIC_STIMULATION_SUCCESS = "ADD_CLINIC_STIMULATION_SUCCESS"
export const ADD_CLINIC_STIMULATION_FAIL = "ADD_CLINIC_STIMULATION_FAIL"

export const UPDATE_CLINIC_STIMULATION = "UPDATE_CLINIC_STIMULATION"
export const UPDATE_CLINIC_STIMULATION_SUCCESS = "UPDATE_CLINIC_STIMULATION_SUCCESS"
export const UPDATE_CLINIC_STIMULATION_FAIL = "UPDATE_CLINIC_STIMULATION_FAIL"

export const DISABLE_CLINIC_STIMULATION = "DISABLE_CLINIC_STIMULATION"
export const DISABLE_CLINIC_STIMULATION_SUCCESS = "DISABLE_CLINIC_STIMULATION_SUCCESS"
export const DISABLE_CLINIC_STIMULATION_FAIL = "DISABLE_CLINIC_STIMULATION_FAIL"

export const ENABLE_CLINIC_STIMULATION = "ENABLE_CLINIC_STIMULATION"
export const ENABLE_CLINIC_STIMULATION_SUCCESS = "ENABLE_CLINIC_STIMULATION_SUCCESS"
export const ENABLE_CLINIC_STIMULATION_FAIL = "ENABLE_CLINIC_STIMULATION_FAIL"

export const CLEAR_STIMULATIONS_ERROR = "CLEAR_STIMULATIONS_ERROR"
export const CLEAR_STIMULATION = "CLEAR_STIMULATION";
export const CLEAR_CLINIC_STIMULATIONS = "CLEAR_CLINIC_STIMULATIONS";

export const GET_LIVE_STIMULATION = "GET_LIVE_STIMULATION"
export const GET_LIVE_STIMULATION_SUCCESS = "GET_LIVE_STIMULATION_SUCCESS"
export const GET_LIVE_STIMULATION_FAIL = "GET_LIVE_STIMULATION_FAIL"
