/* PLATO COUNTRIES */
export const GET_USER_REPORTS = "GET_USER_REPORTS"
export const GET_USER_REPORTS_SUCCESS = "GET_USER_REPORTS_SUCESS"
export const GET_USER_REPORTS_FAIL = "GET_USER_REPORTS_FAIL"

export const GET_USER_REPORTS_LIST = "GET_USER_REPORTS_LIST"
export const GET_USER_REPORTS_LIST_SUCCESS = "GET_USER_REPORTS_LIST_SUCESS"
export const GET_USER_REPORTS_LIST_FAIL = "GET_USER_REPORTS_LIST_FAIL"

export const GET_CHART_REPORTS_LIST = "GET_CHART_REPORTS_LIST"
export const GET_CHART_REPORTS_LIST_SUCCESS = "GET_CHART_REPORTS_LIST_SUCCESS"
export const GET_CHART_REPORTS_LIST_FAIL = "GET_CHART_REPORTS_LIST_FAIL"
