name: Terraform Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'develop'

jobs:
    destroy:
        name: "Destroy GCP for Develop"
        runs-on: ubuntu-latest
        steps:
          - name: Terraform Workspace
            run: terraform workspace new dev | true
            working-directory: ./terraform
            env:
              GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}

          - name: Terraform Select Workspace
            run: terraform workspace select dev
            working-directory: ./terraform
            env:
              GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}

          - name: Terraform Destroy Develop Resources
            id: destroy
            run: terraform destroy -auto-approve
            working-directory: ./terraform
            env:
              GOOGLE_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY }}